### ISSUE TITLE
This repo is out of date

### ISSUE THREAD

**Issue by mindctrl** [MyWorkAus/WP-Remote-WordPress-Plugin#171]
Not all development is being pushed here. The version on wporg is newer. Are you planning to keep this repo updated? Is this your primary development hub for this plugin? Are you planning to push git tags here as well?

**Comment by JeramyNS** [comment]
Hey,

Sorry about that, must have forgot to push up the changes from my local git repo.
We pushed two changes that day because we discovered a bug in websites running older versions of php.
It should be pretty much upto date now.

The only difference between the svn repo and github is a minor change in the readme.
It accidentally read:
* Bug fix for php < 7

but it should have been:
* Bug fix for php 5.4 and lower

This will be modified next time we update the plugin.
